# Generated by Django 5.0 on 2023-12-20 02:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bankuser",
            options={"verbose_name": "Usuario"},
        ),
    ]
