# Generated by Django 5.0 on 2023-12-15 02:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bank", "0002_kindtransacction_code"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="KindTransacction",
            new_name="KindTransaction",
        ),
    ]
