# Generated by Django 5.0 on 2023-12-20 01:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bank", "0004_bankaccount_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=250)),
                ("code", models.CharField(max_length=20)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="KindRequestAperture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=250)),
                ("code", models.CharField(max_length=20)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="kindtransaction",
            name="code",
            field=models.CharField(max_length=20),
        ),
    ]
