# Generated by Django 5.0 on 2023-12-20 01:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bank", "0005_currency_kindrequestaperture_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="bankaccount",
            old_name="number",
            new_name="account_number",
        ),
        migrations.RenameField(
            model_name="bankaccount",
            old_name="actual_amount",
            new_name="balance",
        ),
        migrations.AddField(
            model_name="bankaccount",
            name="currency",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="bank.currency",
            ),
        ),
        migrations.AddField(
            model_name="bankaccount",
            name="linked_accounts",
            field=models.ManyToManyField(null=True, to="bank.bankaccount"),
        ),
        migrations.AddField(
            model_name="bankaccount",
            name="token",
            field=models.CharField(default="", editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name="bankaccount",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="BankRequestAperture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "client_name",
                    models.CharField(max_length=250, verbose_name="Nombre"),
                ),
                ("email", models.EmailField(max_length=260)),
                ("city", models.CharField(max_length=250, verbose_name="Ciudad")),
                ("details", models.TextField(verbose_name="Detalles de la solicitud")),
                (
                    "kind",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="bank.kindrequestaperture",
                        verbose_name="Tipo de solicitud",
                    ),
                ),
            ],
        ),
    ]
