# Generated by Django 5.0 on 2023-12-20 01:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bank", "0006_rename_number_bankaccount_account_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bankaccount",
            name="linked_accounts",
            field=models.ManyToManyField(to="bank.bankaccount"),
        ),
    ]
