# Generated by Django 5.0 on 2023-12-20 02:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bank", "0007_alter_bankaccount_linked_accounts"),
    ]

    operations = [
        migrations.AddField(
            model_name="bankrequestaperture",
            name="is_approved",
            field=models.BooleanField(default=None, null=True),
        ),
    ]
