# Generated by Django 5.0 on 2023-12-20 02:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bank", "0008_bankrequestaperture_is_approved"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bankaccount",
            name="linked_accounts",
            field=models.ManyToManyField(blank=True, to="bank.bankaccount"),
        ),
    ]
