# Generated by Django 5.0 on 2023-12-15 02:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bank", "0003_rename_kindtransacction_kindtransaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="bankaccount",
            name="number",
            field=models.CharField(default="", max_length=20),
            preserve_default=False,
        ),
    ]
